/*
 * mayhem/shecc_abort_shim.h - additive, mayhem-only scaffolding. NOT an upstream edit.
 *
 * shecc uses abort() as its error handler. fatal() / error_at() (src/globals.c) and
 * the "internal invariant / unsupported construct" checks across the parser, register
 * allocator and code generators all print a diagnostic and then call abort(). Fed an
 * invalid or unsupported C input (e.g. the single byte 'A'), the stage-0 compiler
 * therefore terminates with SIGABRT (signal 6). Under Mayhem this fails the baseline
 * sanity check ("terminated with the fatal signal SIGABRT ... on basic inputs") and the
 * run is flagged has_critical_errors; during a real campaign every malformed input (the
 * overwhelming majority of fuzzer-generated bytes) would likewise masquerade as a crash.
 *
 * Fix: redirect shecc's OWN calls to abort() to a clean, non-zero exit(1), so the
 * compiler REJECTS bad input gracefully instead of aborting. This is a compile-time text
 * substitution (-Dabort=shecc_fuzz_reject) applied ONLY to the sanitized fuzz build, via
 * mayhem/build.sh's CC wrapper. It:
 *   - modifies NO upstream source file (purely additive scaffolding);
 *   - leaves the ASan/UBSan runtime untouched - the sanitizers detect real memory /
 *     undefined-behaviour bugs at the point of the violation and halt via their own
 *     internal Die() path (not this libc abort), so genuine bug-finding is preserved;
 *   - leaves shecc's embedded target libc untouched - lib/c.c is inlined into
 *     out/libc.inc as __c("...") STRING literals, which a macro cannot rewrite, so
 *     programs shecc COMPILES keep a working abort().
 * Valid C still runs the full lexer/parser/SSA/codegen/ELF pipeline and exit(0)s with a
 * real ELF emitted - the target is not neutered into a no-op.
 */
#ifndef SHECC_FUZZ_ABORT_SHIM_H
#define SHECC_FUZZ_ABORT_SHIM_H

/*
 * Pull in the real prototypes. -Dabort=shecc_fuzz_reject is already active on the
 * command line, so <stdlib.h>'s `abort` prototype is emitted here as the (void,
 * noreturn) prototype for shecc_fuzz_reject - which the definition below matches. exit()
 * is declared (noreturn) here too, so the noreturn body has no fall-through.
 */
#include <stdio.h>
#include <stdlib.h>

/* Defined once: main.c is a single translation unit that #includes the rest of shecc. */
void shecc_fuzz_reject(void)
{
    /* Flush the diagnostic the caller already printed, then reject cleanly. */
    fflush(NULL);
    exit(1);
}

#endif /* SHECC_FUZZ_ABORT_SHIM_H */
