name: Github Actions

on: [push, pull_request]

jobs:
  host-x86:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [gcc, clang]
        architecture: [arm, riscv]
        link_mode: [static, dynamic]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download dependencies
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -q -y graphviz jq
          sudo apt-get install -q -y qemu-user
          sudo apt-get install -q -y build-essential
          if [ "${{ matrix.link_mode }}" = "dynamic" ]; then
            if [ "${{ matrix.architecture }}" = "arm" ]; then
              sudo apt-get install -q -y gcc-arm-linux-gnueabihf
            else
              # Use the GitHub Releases API to obtain the JSON data of the latest
              # RISC-V toolchain archive
              LATEST_RLS_JSON=$(curl --fail --silent --show-error -L -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/riscv-collab/riscv-gnu-toolchain/releases/latest | jq '.assets | .[] | select(.name == "riscv32-glibc-ubuntu-24.04-gcc.tar.xz")')

              # Retrieve SHA256 and URL
              EXPECTED_SHA256=$(echo $LATEST_RLS_JSON | jq -r .digest | sed 's/sha256://g')
              URL=$(echo $LATEST_RLS_JSON | jq -r .browser_download_url)
              set -eo pipefail

              # Download the toolchain archive
              FILE=/tmp/riscv32-glibc-ubuntu-24.04-gcc.tar.xz
              sudo wget -qO $FILE $URL

              # Verify SHA256
              echo "$EXPECTED_SHA256 $FILE" | sha256sum -c -

              # Extract the archive and add "/opt/riscv/bin" to the system path
              sudo tar Jxf $FILE -C /opt
              echo "/opt/riscv/bin" >> "$GITHUB_PATH"
            fi
          fi
      - name: Determine static or dynamic linking mode
        id: determine-mode
        run: |
          if [ "${{ matrix.link_mode }}" = "dynamic" ]; then
            echo "Use dynamic linking mode"
            echo "DYNLINK=1" >> "$GITHUB_OUTPUT"
          else
            echo "Use static linking mode"
            echo "DYNLINK=0" >> "$GITHUB_OUTPUT"
          fi
      - name: Build artifacts
        env:
          CC: ${{ matrix.compiler }}
        run: |
          make ARCH=${{ matrix.architecture }} DYNLINK=${{ steps.determine-mode.outputs.DYNLINK }}
      - name: IR regression tests
        run: |
          make check-snapshot DYNLINK=${{ steps.determine-mode.outputs.DYNLINK }} || exit 1
      - name: Sanitizer-enabled stage 0 tests
        env:
          CC: ${{ matrix.compiler }}
        run: |
          make check-sanitizer DYNLINK=${{ steps.determine-mode.outputs.DYNLINK }} || exit 1
      - name: Unit tests
        run: |
          make check DYNLINK=${{ steps.determine-mode.outputs.DYNLINK }} || exit 1

  host-arm:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        link_mode: [static, dynamic]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dependencies
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          sudo dpkg --add-architecture armhf
          sudo apt-get update -q -y
          sudo apt-get install -q -y graphviz jq
          sudo apt-get install -q -y build-essential libc6:armhf

          # Use the GitHub Releases API to obtain the JSON data of the latest
          # fastfetch package
          LATEST_RLS_JSON=$(curl --fail --silent --show-error -L -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/fastfetch-cli/fastfetch/releases/latest | jq '.assets | .[] | select(.name == "fastfetch-linux-aarch64.deb")')

          # Retrieve SHA256 and URL
          EXPECTED_SHA256=$(echo $LATEST_RLS_JSON | jq -r .digest | sed 's/sha256://g')
          URL=$(echo $LATEST_RLS_JSON | jq -r .browser_download_url)
          set -eo pipefail

          # Download the fastfetch package
          FILE=/tmp/fastfetch-linux-aarch64.deb
          sudo wget -qO $FILE $URL

          # Verify SHA256
          echo "$EXPECTED_SHA256 $FILE" | sha256sum -c -

          # Install fastfetch
          sudo dpkg -i /tmp/fastfetch-linux-aarch64.deb

      - name: Determine static or dynamic linking mode
        id: determine-mode
        run: |
          if [ "${{ matrix.link_mode }}" = "dynamic" ]; then
            echo "Use dynamic linking mode"
            echo "DYNLINK=1" >> "$GITHUB_OUTPUT"
          else
            echo "Use static linking mode"
            echo "DYNLINK=0" >> "$GITHUB_OUTPUT"
          fi

      - name: Build artifacts
        run: |
          make ARCH=arm DYNLINK=${{ steps.determine-mode.outputs.DYNLINK }}

      - name: Sanitizer-enabled stage 0 tests
        run: |
          make check-sanitizer DYNLINK=${{ steps.determine-mode.outputs.DYNLINK }} || exit 1

      - name: Unit tests
        run: |
          make check DYNLINK=${{ steps.determine-mode.outputs.DYNLINK }} || exit 1

  preprocessor-host:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [gcc, clang]
        architecture: [arm, riscv]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download dependencies
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -q -y graphviz jq
          sudo apt-get install -q -y qemu-user
          sudo apt-get install -q -y build-essential
      - name: Configurate config
        run: |
          make distclean config ARCH=${{ matrix.architecture }}
      - name: Preprocess stage 1 source code
        env:
          CC: ${{ matrix.compiler }}
        run: |
          make out/shecc
          ./out/shecc -E src/main.c > ./out/out.c
      - name: Build stage 1 artifact
        run: |
          ./out/shecc --no-libc -o out/shecc-stage1.elf ./out/out.c

  coding-style:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Coding convention
      run: |
            sudo apt-get install -q -y clang-format-18
            .ci/check-newline.sh
            .ci/check-format.sh
      shell: bash
